typo_dict = {
    'a': 'qwsxz',
    'b': 'vfghn',
    'c': 'xsdfv',
    'd': 'wersfxcv',
    'e': 'wsdfr',
    'f': 'ertdgcvb',
    'g': 'rtyfhvbn',
    'h': 'tyugjbnm',
    'i': 'ujklo',
    'j': 'yuihknm',
    'k': 'uiojlm',
    'l': 'iopk',
    'm': 'nhjk',
    'o': 'iklp',
    'p': 'ol',
    'q': 'asw',
    'r': 'edfgt',
    's': 'qweadzxc',
    't': 'rfghy',
    'u': 'yhjki',
    'v': 'cdfgb',
    'w': 'qasde',
    'x': 'zasdc',
    'y': 'tghju',
    'z': 'asx',
}
